# Introduction to Numpy
---
## importing

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/home/codespace/.local/lib/python3.12/site-packages/numpy/__init__.py'>

# One-dimentional Arrays
---
## creating array with 
1. all zeros 
2. all ones
2. all a given no.

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

## python list to numpy array

In [6]:
a = np.array([10, 20, 14, 28])
a

array([10, 20, 14, 28])

## elements from to a certain range

In [7]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

## create a array within the range of 0 to 1 of size 11

In [8]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

# Multi-dimentional Arrays
---

In [9]:
np.zeros((5, 2)) # (rows, columns)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
n[1, 0]

np.int64(4)

In [17]:
n[0][1]

np.int64(2)

In [20]:
n[2] #get row

array([7, 8, 9])

In [21]:
n[:, 1] #get column

array([2, 5, 8])

# Randomly Generated Array
---

In [25]:
np.random.seed(10) #to get the same output everytime (can use anything in place of 10)
np.random.rand(5,2) # range(0,1)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [26]:
np.random.seed(10) 
np.random.randn(5,2) #normal standard distribution

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385],
       [ 0.62133597, -0.72008556],
       [ 0.26551159,  0.10854853],
       [ 0.00429143, -0.17460021]])

In [27]:
np.random.randint(low = 0, high = 100, size = (5, 2)) #integers

array([[62, 33],
       [72, 78],
       [49, 51],
       [54, 77],
       [69, 13]])

# Element wise Operations
---

In [28]:
a = np.arange(0, 5)
a

array([0, 1, 2, 3, 4])

In [39]:
b = np.array([3, 1, 1, 5, 0])
b

array([3, 1, 1, 5, 0])

In [40]:
a * b

array([ 0,  1,  2, 15,  0])

## Comparision Operations

In [41]:
a >= 2

array([False, False,  True,  True,  True])

In [42]:
a > b

array([False, False,  True, False,  True])

In [43]:
a[a > b]

array([2, 4])

## Summarizing Operations

In [44]:
a.min()

np.int64(0)

In [45]:
a.max()

np.int64(4)

In [46]:
a.sum()

np.int64(10)

In [48]:
a.mean()

np.float64(2.0)

In [50]:
a.std() #standard deviation

np.float64(1.4142135623730951)

### Cheatsheet : https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python