# Linear Algebra
---

## Dot Product
___

In [2]:
import numpy as np

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [5]:
u = np.array([2, 4, 6, 8])
v = np.array([3, 4, 1, 2])

In [10]:
vector_vector_multiplication(u, v)

np.float64(44.0)

### or

In [11]:
u.dot(v)

np.int64(44)

---

In [12]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [13]:
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1],
             ])

In [14]:
matrix_vector_multiplication(U, v)

array([39., 16., 17.])

### or

In [15]:
U.dot(v)

array([39, 16, 17])

---

In [17]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [16]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [18]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [19]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Inverse of Matrix

---

In [21]:
Vs = V[[0, 1, 2]]
Vs #inverse exist only for square matrices

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [22]:
np.linalg.inv(Vs)

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])